= Overview

== What is TrustyAI?

TrustyAI is, at its core, a Java library and service for Explainable AI (XAI).
TrustyAI offers fairness metrics, explainable AI algorithms, and xref:features.adoc[various other XAI tools] at a library-level as well as a containerized service and Kubernetes deployment.
TrustyAI consists of several components, including:

* xref:trustyai-core.adoc[TrustyAI core], the core TrustyAI Java module, containing fairness metrics, AI explainers, and other XAI utilities.
* xref:trustyai-service.adoc[TrustyAI service], TrustyAI-as-a-service, a REST service for fairness metrics and explainability algorithms including ModelMesh integration.
* xref:trustyai-operator.adoc[TrustyAI operator], a Kubernetes operator for TrustyAI service.
* xref:python-trustyai.adoc[Python TrustyAI], a Python library allowing the usage of TrustyAI's toolkit from Jupyter notebooks

== Glossary

[horizontal]
XAI::
XAI refers to artificial intelligence systems designed to provide clear, understandable explanations of their decisions and actions to human users.
Fairness::
AI fairness refers to the design, development, and deployment of AI systems in a way that ensures they operate equitably and do not include biases or discrimination against any individual or group.
